# Generated by Django 4.2.2 on 2023-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=200)),
                ('qaddress', models.CharField(max_length=200)),
                ('qemail', models.EmailField(max_length=200)),
                ('qphone', models.IntegerField(max_length=200)),
                ('query', models.TextField(max_length=200)),
            ],
        ),
    ]
